sudo: required

services:
  - docker

env:
  global:
    - TAGS="18.06-ar71xx 18.06-x86-64"
    - DOCKERHUB_REPO=openwrt-sdk

before_install:
  - docker version
  - docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPO:base -f Dockerfile.base .

script:
  - for TAG in $TAGS; do
      docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPO:$TAG -f Dockerfile.$TAG .;
    done

deploy:
  provider: script
  script:
    - docker login -u=$DOCKERHUB_USER -p=$DOCKERHUB_PASSWORD
    - docker push $DOCKERHUB_USER/$DOCKERHUB_REPO
  on:
    branch: master
