sudo: required

services:
  - docker

env:
  global:
    - TAGS=""
    - IMAGE_NAME="${DOCKERHUB_USER}/openwrt-sdk"

before_install:
  - docker version
  - docker build --pull --cache-from "${IMAGE_NAME}:base" -t "${IMAGE_NAME}:base" -f Dockerfile.base .

script:
  - for TAG in $TAGS; do
      docker build --pull --cache-from "${IMAGE_NAME}:$TAG" -t "${IMAGE_NAME}:$TAG" -f "Dockerfile.$TAG" .;
    done

before_deploy:
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"

deploy:
  provider: script
  script: docker push "$IMAGE_NAME"
  on:
    branch: master
